### ISSUE TITLE
"Model not found" error on server start

### ISSUE THREAD

**Issue by niloofaryousefi** [chathika/Py2NetLogo-Forked#3]
"Model not found" error is generated on server start. However, the server functions after starting. Tested on Python 3.6.5.

**Comment by chathika** [comment]
This seems to be an error caused by a diagnostic check by the server once it starts. The server tries to start a model from the NetLogo Sample Models directory to check if it has started right. This has been tested on Windows, but on MacOS this would fail since the NetLogo directory structure between Windows and MacOs builds are different.

This issue will be fixed in the next minor revision.

**Comment by chathika** [comment]
This bug has been addressed in [v0.2.0](https://github.com/chathika/NL4Py/releases/tag/v0.2.0)
